version: '3.8'

services:
  redis:
    image: redis
    restart: always
    network_mode: "host"
    command: redis-server --save 20 1 --loglevel warning --requirepass mypass
    volumes: 
      - redis:/data
volumes:
  redis:
    driver: local