version: '3.8'

services:
  redis:
    image: redis
    restart: always
    networks: 
      - base
    ports:
      - "6379:6379"
    command: redis-server --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass mypass
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  redis:
    driver: local
networks:
  base:
    driver: bridge